name: run program

on: 
  push:
  workflow_dispatch:
    inputs:
      use-matrix:
        type: boolean
        description: Use Matrix
        default: false


jobs:
  execute-index:
        strategy:
          matrix:
            PORT: [8080, 3000]
        env:
          PORT: ${{ inputs.use-matrix == true && matrix.PORT || 1 }}
        runs-on: ubuntu-latest
        steps:
            - name: fetch repo
              uses: actions/checkout@v4

            - name: run index js
              run: node index.js
