name: run program

on: push

jobs:
    execute-index:
        runs-on: ubuntu-latest
        steps:
            - name: fetch repo
              run: actions/checkout@v4

            - name: run index js
              run: node index.js
