name: run program

on: [push, workflow_dispatch]

env:
  PORT: 3000

jobs:
    execute-index:
        runs-on: ubuntu-latest
        steps:
            - name: fetch repo
              uses: actions/checkout@v4

            - name: run index js
              run: node index.js
